services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15.3
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - postgres
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
  postgres:

volumes:
  postgres-db-data:
